# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='team_heading',
            field=models.CharField(default='Team Slogun', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_name',
            field=models.CharField(default='Team Member name', max_length=300),
        ),
    ]
