# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:04
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20160403_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='team_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
